---
# tasks file for configure-elastic-file
- name: Configure elasticsearch.yml File
  copy:
    src: '{{item.src}}'
    dest: /etc/elasticsearch/elasticsearch.yml
    owner: root
    group: elasticsearch
  with_items:
    - { src: 'path/to/you/conf/file.yml'}
