---
# tasks file for systemd-conf
- name: Add or modify memlock, both soft and hard, limit for elasticsearch user.
  pam_limits:
    domain: elasticsearch
    limit_type: '-'
    limit_item: memlock
    value: unlimited
    comment: unlimited memory lock for elasticsearch

- name: set LimitMEMLOCK to infinity.
  lineinfile:
    path: /usr/lib/systemd/system/elasticsearch.service
    insertafter: 'LimitAS-infinity'
    line: 'LimitMEMLOCK=infinity'
    state: present

- name: set vm.max_map_count to 262144 in sysctl
  sysctl: name={{ item.key }} value={{ item.value }}
  with_items:
    - { key: "vm.max_map_count", value: "262144" }

- name: For a permanent setting, update vm.max_map_count in /etc/sysctl.conf
  command: sysctl -p /etc/sysctl.conf
